
package view;

import dados.DBCampus;
import dados.DBCategoria;
import dados.DBItem;
import dados.DBLocalizacao;
import dados.DBResponsavel;
import dados.DBStatus;
import javax.net.ssl.SSLEngineResult.Status;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import javax.xml.bind.ParseConversionEvent;
import model.Campus;
import model.Categoria;
import model.Fornecedor;
import model.Item;
import model.Localizacao;
import model.Responsavel;

/**
 *
 * @author Ricardo
 */
public class Tela_Item_CadastroLote extends javax.swing.JPanel {

    /** Creates new form Tela_Item_CadastroLote */
    public Tela_Item_CadastroLote() {
        initComponents();
        
        //preenche dados dos comboBoxs
        preencheDadosFormulario();
        
        
        //esconde o formulário interno de cadastro de fornecedor
        panelCadInternoFornecedor.setVisible(false);
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoRegPatInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoRegPatFinal = new javax.swing.JTextField();
        campoMarca = new javax.swing.JTextField();
        campoValor = new javax.swing.JTextField();
        botaoCadastrarItensLote = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        campoNumNF = new javax.swing.JTextField();
        campoNumEmpenho = new javax.swing.JTextField();
        ComboBoxCampus = new javax.swing.JComboBox();
        ComboBoxLocalizacao = new javax.swing.JComboBox();
        campoNumLicitacao = new javax.swing.JTextField();
        ComboBoxStatus = new javax.swing.JComboBox();
        ComboBoxCategoria = new javax.swing.JComboBox();
        campoDataEmissaoNF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ComboBoxResponsavel = new javax.swing.JComboBox();
        botaoVerificarFornecedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescricao = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        campoFornecedor = new javax.swing.JFormattedTextField();
        panelCadInternoFornecedor = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        campoCNPJCadastroFornecedor = new javax.swing.JFormattedTextField((setMascara("##.###.###/####-##")));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 281));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tela Cadastro em Lote Item");

        jLabel2.setText("Registro patrimonial:");

        jLabel3.setText("Descrição:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Valor:");

        campoRegPatInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRegPatInicialActionPerformed(evt);
            }
        });

        jLabel6.setText("De:");

        jLabel7.setText("Até:");

        botaoCadastrarItensLote.setText("Cadastrar");
        botaoCadastrarItensLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarItensLoteActionPerformed(evt);
            }
        });

        jLabel8.setText("Número Nota Fiscal:");

        jLabel9.setText("Número Empenho:");

        jLabel10.setText("Fornecedor (CNPJ):");

        jLabel11.setText("Localização:");

        jLabel12.setText("Campus:");

        jLabel13.setText("Nº Licitação:");

        jLabel14.setText("Status:");

        jLabel15.setText("Categoria:");

        campoNumNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumNFActionPerformed(evt);
            }
        });

        ComboBoxCampus.setModel(new javax.swing.DefaultComboBoxModel());

        ComboBoxLocalizacao.setModel(new javax.swing.DefaultComboBoxModel());

        ComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel());

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel());

        jLabel16.setText("Data Emissão NF:");

        jLabel17.setText("Responsável:");

        ComboBoxResponsavel.setModel(new javax.swing.DefaultComboBoxModel());

        botaoVerificarFornecedor.setText("Verificar Fornecedor");
        botaoVerificarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerificarFornecedorActionPerformed(evt);
            }
        });

        campoDescricao.setColumns(20);
        campoDescricao.setRows(5);
        jScrollPane1.setViewportView(campoDescricao);

        jLabel24.setText("AQUI VAI FORNECEDOR OK OU NÃO OK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(campoNumNF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(campoDataEmissaoNF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNumEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(campoNumLicitacao, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(365, 365, 365))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoRegPatInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoRegPatFinal))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(ComboBoxCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxResponsavel, 0, 216, Short.MAX_VALUE))
                        .addContainerGap(55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoVerificarFornecedor))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCadastrarItensLote, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(834, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoRegPatInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(campoRegPatFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDataEmissaoNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campoNumEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoNumLicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoVerificarFornecedor))))
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarItensLote)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelCadInternoFornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Cadastro Fornecedor");

        jLabel19.setText("CNPJ:");

        jLabel20.setText("Nome:");

        jLabel21.setText("Telefone:");

        jLabel22.setText("Email:");

        jLabel23.setText("Representante:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar Fornecedor");

        javax.swing.GroupLayout panelCadInternoFornecedorLayout = new javax.swing.GroupLayout(panelCadInternoFornecedor);
        panelCadInternoFornecedor.setLayout(panelCadInternoFornecedorLayout);
        panelCadInternoFornecedorLayout.setHorizontalGroup(
            panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                        .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(campoCNPJCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap(578, Short.MAX_VALUE))
        );
        panelCadInternoFornecedorLayout.setVerticalGroup(
            panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCNPJCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCadInternoFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCadInternoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void campoRegPatInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRegPatInicialActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_campoRegPatInicialActionPerformed

private void botaoCadastrarItensLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarItensLoteActionPerformed
    
        int registroInicial = Integer.parseInt(campoRegPatInicial.getText().toString());
        int registroFinal = Integer.parseInt(campoRegPatFinal.getText().toString());
        
        for(int i = registroInicial; i <= registroFinal; i++){
        
            
            Item item = new Item();
            
            item.setCodigoRP( i );
            
            item.setDescricao( campoDescricao.getText().toString() );
            
            item.setMarca( campoMarca.getText().toString() );
            
            item.setValor( Double.parseDouble( campoValor.getText().toString() ) );
            
            item.setNumeroNF( Integer.parseInt( campoNumNF.getText().toString() ) );
            
            item.setDataEmissaoNF( Integer.parseInt( campoDataEmissaoNF.getText().toString() ) );
            
            item.setNumeroEmpenho( Integer.parseInt( campoNumEmpenho.getText().toString() ) );
            
            item.setLicitacao( Integer.parseInt( campoNumLicitacao.getText().toString() ) );     
            
      
            Fornecedor fornecedor = new Fornecedor();
            //fornecedor.setCnpj( Integer.parseInt( campoFornecedor.getText().toString() ) );
            //campoFornecedor = new javax.swing.JFormattedTextField((setMascara("##.###.###/####-##")));
            fornecedor.setCnpj( Integer.parseInt( campoFornecedor.getText().toString() ) );
          
 
            
            
            
            
            //fornecedor.setCnpj( Integer.parseInt(  campoFornecedorxx ));
            fornecedor.setCnpj( 999 );
            
            item.setFornecedor( fornecedor );
            
            Localizacao localizacao = new Localizacao();
            localizacao.setId( obtemIndexSelecLocalizacao() );
            
            item.setLocalizacao( localizacao );

            Campus campus = new Campus();
            campus.setId( obtemIndexSelecCampus() );
            
            item.setCampus( campus );
            
            model.Status status = new model.Status();
            status.setId( obtemIndexSelecStatus()  );
            
            item.setStatus(status);
            
            
            Categoria categoria = new Categoria();
            categoria.setIdCategoria( obtemIndexSelecCategoria()  );

            item.setCategoria( categoria );
            
            
            Responsavel responsavel = new Responsavel();
            
            responsavel.setSiape( obtemIndexSelecResponsavel() );
            
            item.setResponsavel( responsavel );
            
            
            
            item.inserirItem(); 
            
            
            

        }
        
        JOptionPane.showMessageDialog(null, "Cadastro realizado com Sucesso!");        
        
        
         //limpa todos os campos
         campoDescricao.setText("");
         campoMarca.setText("");
         campoValor.setText("");
         campoRegPatInicial.setText("");
         campoRegPatFinal.setText("");
         campoNumNF.setText("");
         campoDataEmissaoNF.setText("");
         campoNumEmpenho.setText("");
         campoNumLicitacao.setText("");
         campoFornecedor.setText("");
         ComboBoxLocalizacao.setSelectedIndex(0);
         ComboBoxCampus.setSelectedIndex(0);
         ComboBoxCategoria.setSelectedIndex(0);
         ComboBoxResponsavel.setSelectedIndex(0);
         ComboBoxStatus.setSelectedIndex(0);
         
                

    
    
}//GEN-LAST:event_botaoCadastrarItensLoteActionPerformed


private void campoNumNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumNFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_campoNumNFActionPerformed

private void botaoVerificarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerificarFornecedorActionPerformed

    
    panelCadInternoFornecedor.setVisible(true);
    
    
}//GEN-LAST:event_botaoVerificarFornecedorActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxCampus;
    private javax.swing.JComboBox ComboBoxCategoria;
    private javax.swing.JComboBox ComboBoxLocalizacao;
    private javax.swing.JComboBox ComboBoxResponsavel;
    private javax.swing.JComboBox ComboBoxStatus;
    private javax.swing.JButton botaoCadastrarItensLote;
    private javax.swing.JButton botaoVerificarFornecedor;
    private javax.swing.JFormattedTextField campoCNPJCadastroFornecedor;
    private javax.swing.JTextField campoDataEmissaoNF;
    private javax.swing.JTextArea campoDescricao;
    private javax.swing.JFormattedTextField campoFornecedor;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoNumEmpenho;
    private javax.swing.JTextField campoNumLicitacao;
    private javax.swing.JTextField campoNumNF;
    private javax.swing.JTextField campoRegPatFinal;
    private javax.swing.JTextField campoRegPatInicial;
    private javax.swing.JTextField campoValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel panelCadInternoFornecedor;
    // End of variables declaration//GEN-END:variables

   public MaskFormatter setMascara(String mascara){  
       
       //para a aplicação no textField
       //# = qualquer numero válido
       //U = qualquer caractere, as letras minusculas são formatadas em maiuscula.
       //L = qualquer caractere, as letras maiusculas são formatadas em minusculas.
       //A = qualquer caractere ou numero.
       
       
       MaskFormatter mask = null;  
      try{  
         mask = new MaskFormatter(mascara);                    
         }catch(java.text.ParseException ex){}  
      return mask;  
   }  
   
    public String removeCaracEspeciais(String str){
            
        
        //Troca os caracteres especiais da string por "" 
        String[] caracteresEspeciais = {"\\.", ",", "-", ":", "\\(", "\\)", "ª", "\\|", "\\\\", "°", "/"};
 
        for (int i = 0; i < caracteresEspeciais.length; i++) {
            str = str.replaceAll(caracteresEspeciais[i], "");
        }

        /** Troca os espaços no início por "" **/
        str = str.replaceAll("^\\s+", "");
        /** Troca os espaços no início por "" **/
        str = str.replaceAll("\\s+$", "");
        /** Troca os espaços duplicados, tabulações e etc por  " " **/
        str = str.replaceAll("\\s+", " ");
        
        
        return str;
    }

   
   

    public void preencheComboBoxLocalizacao(){
        
        ComboBoxLocalizacao.removeAllItems();
       try{
          DBLocalizacao dbLocalizacao = new DBLocalizacao();

           dbLocalizacao.select("*" ,"order by idlocalizacao asc");

           ComboBoxLocalizacao.addItem("");

           while( dbLocalizacao.getResultSet().next() ){

                ComboBoxLocalizacao.addItem( dbLocalizacao.getResultSet().getString("idlocalizacao").toString()+" | Prédio: "+dbLocalizacao.getResultSet().getString("predio").toString()+" | Sala: "+dbLocalizacao.getResultSet().getString("sala").toString());
           } 
                    
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    }

    public void preencheComboBoxCampus(){
        
       ComboBoxCampus.removeAllItems();
       try{
           DBCampus dbCampus = new DBCampus();

           dbCampus.select("*"," order by id asc");

           
           ComboBoxCampus.addItem("");

           while( dbCampus.getResultSet().next() ){

                ComboBoxCampus.addItem( dbCampus.getResultSet().getString("id").toString()+" | Campus: "+dbCampus.getResultSet().getString("campus").toString());
           } 
                    
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    }
    
    
     public void preencheComboBoxStatus(){
         
       ComboBoxStatus.removeAllItems();  
       try{
           DBStatus dbStatus = new DBStatus();

           dbStatus.select("*", " order by idstatus asc");

           

           
           ComboBoxStatus.addItem("");

           while( dbStatus.getResultSet().next() ){

                ComboBoxStatus.addItem( dbStatus.getResultSet().getString("idstatus").toString()+" | Status: "+dbStatus.getResultSet().getString("status").toString());
           } 
                    
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    }
    
    public void preencheComboBoxCategoria(){

       ComboBoxCategoria.removeAllItems();
       try{
           DBCategoria dbCategoria = new DBCategoria();

           dbCategoria.select("*", " order by idcategoria asc");

           

           
           ComboBoxCategoria.addItem("");

           while( dbCategoria.getResultSet().next() ){

                ComboBoxCategoria.addItem( dbCategoria.getResultSet().getString("idcategoria").toString()+" | Categoria: "+dbCategoria.getResultSet().getString("nome").toString());
           } 
                    
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    } 
    
    
    
    public void preencheComboBoxResponsavel(){

       ComboBoxResponsavel.removeAllItems();
       try{
           
           DBResponsavel dbResponsavel = new DBResponsavel();

           dbResponsavel.select("*", " order by siape asc");

           

           
           ComboBoxResponsavel.addItem("");

           while( dbResponsavel.getResultSet().next() ){

                ComboBoxResponsavel.addItem( dbResponsavel.getResultSet().getString("siape").toString()+" | Nome: "+dbResponsavel.getResultSet().getString("nome").toString());
           } 
                    
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    } 
     
    public void preencheDadosFormulario(){
    
        
        preencheComboBoxLocalizacao();
        preencheComboBoxCampus();
        preencheComboBoxStatus();
        preencheComboBoxCategoria();
        preencheComboBoxResponsavel();
    
    }
    
    public int obtemIndexSelecLocalizacao(){
       
      
       try{
           DBLocalizacao dbLocalizacao = new DBLocalizacao();
           dbLocalizacao.select("*", " order by idlocalizacao asc");
           
           int idBD = 0;
           int cont = 1; 
           while( dbLocalizacao.getResultSet().next() ){

               if( cont == ComboBoxLocalizacao.getSelectedIndex()  ){
               
                   idBD = dbLocalizacao.getResultSet().getInt("idlocalizacao");
               }
               cont++;
           } 
           
           //System.out.println( "LOCALIZAÇÃO DB: "+idBD);
           return idBD;
           
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
        
       return 0;
    }
    
    public int obtemIndexSelecCampus(){
        
       try{
           DBCampus dbCampus = new DBCampus();
           dbCampus.select("*", "order by id asc");

           int idBD = 0;
           int cont = 1; 
           while( dbCampus.getResultSet().next() ){

               if( cont == ComboBoxCampus.getSelectedIndex()  ){
               
                   idBD = dbCampus.getResultSet().getInt("id");
               }
               cont++;
           }
           
           //System.out.println( "CAMPUS DB: "+idBD);
           return idBD;
           
           
           
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
       
        return 0;
    }
    
    
    public int obtemIndexSelecStatus(){
        
       try{
           DBStatus dbStatus = new DBStatus();
           dbStatus.select("*", " order by idstatus asc");

           int idBD = 0;
           int cont = 1; 
           while( dbStatus.getResultSet().next() ){

               if( cont == ComboBoxStatus.getSelectedIndex()  ){
               
                   idBD = dbStatus.getResultSet().getInt("idstatus");
               }
               cont++;
           }
           
           //System.out.println( "STATUS DB: "+idBD);
           return idBD;
           
           
           
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
       
        return 0;
    }

    public int obtemIndexSelecCategoria(){
        
       try{
           DBCategoria dbCategoria = new DBCategoria();
           dbCategoria.select("*", " order by idcategoria asc");

           int idBD = 0;
           int cont = 1; 
           while( dbCategoria.getResultSet().next() ){

               if( cont == ComboBoxCategoria.getSelectedIndex()  ){
               
                   idBD = dbCategoria.getResultSet().getInt("idcategoria");
               }
               cont++;
           }
           
           //System.out.println( "CATEGORIA DB: "+idBD);
           return idBD;
           
           
           
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
       
        return 0;
    }

    
    public int obtemIndexSelecResponsavel(){
        
       try{
           DBResponsavel dbResponsavel = new DBResponsavel();
           dbResponsavel.select("*", " order by siape asc");

           int idBD = 0;
           int cont = 1; 
           while( dbResponsavel.getResultSet().next() ){

               if( cont == ComboBoxResponsavel.getSelectedIndex()  ){
               
                   idBD = dbResponsavel.getResultSet().getInt("siape");
               }
               cont++;
           }
           
           //System.out.println( "CATEGORIA DB: "+idBD);
           return idBD;
           
           
           
        }catch(Exception erro){
        
            //JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
       
        return 0;
    }
    
    
    
    
    
    
    
    
    
}
